eureka:
    instance:
        hostname: localhost
        instance-id: ${spring.application.name}:${random.uuid}
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

spring:
    cloud:
        config:
            allowOverride: true
            overrideNone: true
            overrideSystemProperties: false