eureka:
    instance:
        hostname: localhost

management:
    endpoints:
        web:
            exposure:
                include: health, refresh, beans, metrics, prometheus
        health:
            show-details: always